app/django_eshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_module.urls')),
    path('', include('account_module.urls')),
    path('contact-us/', include('contact_us_module.urls')),
    path('products/', include('product_module.urls')),
    path('order/', include('order_module.urls')),
    path('user/', include('user_panel_module.urls')),
    # path('api/', include('api_module.urls')),
    path('api/product/', include('product_api_module.urls')),
    path('api/slider/', include('site_api_module.urls')),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path('api/auth/', include('drf_social_oauth2.urls', namespace='drf')),

]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'home_module.views.error_404_view'

app/home_module/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home_page'),
    path('about-us', views.AboutView.as_view(), name='about_page'),

]

app/site_module/models.py
from django.db import models


# Create your models here.
class SiteSetting(models.Model):
    site_name = models.CharField(max_length=200, verbose_name='نام سایت')
    site_url = models.CharField(max_length=200, verbose_name='دامنه سایت')
    address = models.CharField(max_length=200, verbose_name='آدرس')
    phone = models.CharField(max_length=200, null=True, blank=True, verbose_name='تلفن')
    fax = models.CharField(max_length=200, null=True, blank=True, verbose_name='فکس')
    email = models.CharField(max_length=200, null=True, blank=True, verbose_name='ایمیل')
    copy_right = models.TextField(verbose_name='متن کپی رایت سایت')
    about_us_text = models.TextField(verbose_name='متن درباره ما سایت')
    site_logo = models.ImageField(upload_to='images/site-setting/', verbose_name='لوگو سایت')
    is_main_setting = models.BooleanField(verbose_name='تنظیمات اصلی')

    class Meta:
        verbose_name = 'تنظیمات سایت'
        verbose_name_plural = 'تنظیمات'

    def __str__(self):
        return self.site_name


class FooterLinkBox(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان')

    class Meta:
        verbose_name = 'دسته بندی لینک های فوتر'
        verbose_name_plural = 'دسته بندی های لینک های فوتر'

    def __str__(self):
        return self.title


class FooterLink(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان')
    url = models.URLField(max_length=500, verbose_name='لینک')
    footer_link_box = models.ForeignKey(to=FooterLinkBox, on_delete=models.CASCADE, verbose_name='دسته بندی')

    class Meta:
        verbose_name = 'لینک فوتر'
        verbose_name_plural = 'لینک های فوتر'

    def __str__(self):
        return self.title


class Slider(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان')
    url = models.URLField(max_length=500, verbose_name='لینک')
    url_title = models.CharField(max_length=200, verbose_name='عنوان لینک')
    description = models.TextField(verbose_name='توضیحات اسلایدر', blank=True, null=True)
    image = models.ImageField(upload_to='images/sliders', verbose_name='تصویر اسلایدر')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')

    class Meta:
        verbose_name = 'اسلایدر'
        verbose_name_plural = 'اسلایدر ها'
        ordering = ('-id',)

    def __str__(self):
        return self.title


class SiteBanner(models.Model):
    class SiteBannerPositions(models.TextChoices):
        product_list = 'product_list', 'صفحه لیست محصولات',
        product_detail = 'product_detail', 'صفحه ی جزییات محصولات',
        about_us = 'about_us', 'درباره ما'

    title = models.CharField(max_length=200, verbose_name='عنوان بنر')
    url = models.URLField(max_length=400, null=True, blank=True, verbose_name='آدرس بنر')
    image = models.ImageField(upload_to='images/banners', verbose_name='تصویر بنر')
    is_active = models.BooleanField(verbose_name='فعال / غیرفعال')
    position = models.CharField(max_length=200, choices=SiteBannerPositions.choices, verbose_name='جایگاه نمایشی')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'بنر تبلیغاتی'
        verbose_name_plural = 'بنرهای تبلیغاتی'

app/templates/shared/_layout.html
{% load render_partial %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mehran">
    <title>{% block title %}{% endblock %}</title>
    {% include 'shared/header_references.html' %}
    {% block header_references %}{% endblock %}
</head>
<body>
{% render_partial 'home_module.views.site_header_component' %}
{% block content %}{% endblock %}
{% render_partial 'home_module.views.site_footer_component' %}
{% include 'shared/footer_references.html' %}
{% block footer_references %}{% endblock %}
</body>

</html>

app/templates/shared/footer_references.html
{% load static %}
<script src="{% static "js/jquery.js" %}"></script>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
{#<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>#}
{#<script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>#}
{#<script type="text/javascript" src="{% static "slick/slick.min.js" %}"></script>#}
{#<script href="{% static 'js/slick.min.js' %}"></script>#}
{#<script href="{% static 'js/custom_slick.js' %}"></script>#}
<script src="{% static "js/bootstrap.min.js" %}"></script>
{#<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>#}
{#<script src="/static/js/bootstrap.min.js"></script>#}

{#<script src="/static/js/jquery.scrollUp.min.js"></script>#}
<script src="{% static "js/jquery.scrollUp.min.js" %}"></script>

{#<script src="/static/js/price-range.js"></script>#}
<script src="{% static "js/price-range.js" %}"></script>
{#<script src="/static/js/jquery.prettyPhoto.js"></script>#}
<script src="{% static "js/jquery.prettyPhoto.js" %}"></script>
{#<script src="/static/js/main.js"></script>#}
<script src="{% static "js/main.js" %}"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{#<script src="/static/js/custom.js"></script>#}
<script src="{% static "js/custom.js" %}"></script>

app/templates/shared/header_references.html
{% load static %}


<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css">

<link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet">
<link href="{% static "css/prettyPhoto.css" %}" rel="stylesheet">
<link href="{% static "css/price-range.css" %}" rel="stylesheet">
<link href="{% static "css/animate.css" %}" rel="stylesheet">
<link href="{% static "css/main.css" %}" rel="stylesheet">
<link href="{% static "css/responsive.css" %}" rel="stylesheet">
{#<link href="{% static "css/custom.css" %}" rel="stylesheet">#}


<!--[if lt IE 9]>
{#<script src="{% static "" %}js/html5shiv.js"></script>#}
{#<script src="{% static "" %}js/respond.min.js"></script>#}
<![endif]-->
<link rel="shortcut icon" href="{% static "images/ico/favicon.ico" %}">

{#<link rel="apple-touch-icon-precomposed" sizes="144x144"#}
{#      href="{% static "" %}images/ico/apple-touch-icon-144-precomposed.png">#}
{#<link rel="apple-touch-icon-precomposed" sizes="114x114"#}
{#      href="{% static "" %}images/ico/apple-touch-icon-114-precomposed.png">#}
{#<link rel="apple-touch-icon-precomposed" sizes="72x72"#}
{#      href="{% static "" %}images/ico/apple-touch-icon-72-precomposed.png">#}
{#<link rel="apple-touch-icon-precomposed" href="{% static "" %}images/ico/apple-touch-icon-57-precomposed.png">#}

app/templates/shared/site_footer_component.html
<footer id="footer" class="rtl"><!--Footer-->
    <div class="footer-Before">
        <div class="container">
            <div class="block-news">
                <div class="row">
                    <h3>با عضویت در خبـرنامه ما از تخفیفات ویـژه ما با خبـر شوید ... </h3>
                    <div class="searchform newslatter">
                        <input type="text" placeholder="آدرس ایمیـل شما ..."/>
                        <button type="submit" class="btn btn-default">
                            <i class="fa fa-arrow-circle-o-left"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-top">

        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <div class="address">
                        <img src="/static/images/home/map.png" alt=""/>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="address">
                        <img src="/static/images/home/map.png" alt=""/>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="companyinfo">
                        <h2>{{ site_setting.site_name }}</h2>
                        <h4>درباره ما :</h4>
                        <p>{{ site_setting.about_us_text }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-widget">
        <div class="container">
            <div class="row">
                {% for footer_link_box in footer_link_boxes %}
                    <div class="col-sm-3 pull-right">
                        <div class="single-widget">
                            <h2>{{ footer_link_box.title }}</h2>
                            <ul class="nav nav-pills nav-stacked">
                                {% for link in footer_link_box.footerlink_set.all %}
                                    <li><a href="{{ link.url }}">{{ link.title }}</a></li>
                                {% endfor %}

                            </ul>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>

    <div class="footer-bottom" style="direction: ltr !important;">
        <div class="container">
            <div class="row">
                <p class="pull-right">
                    {{ site_setting.copy_right }}
                </p>
            </div>
        </div>
    </div>

</footer><!--/Footer-->

app/templates/shared/site_header_component.html
<header id="header"><!--header-->
    <div class="header_top"><!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> </a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle"><!--header-middle-->
        <div class="container">
            <div class="row">
                <!-- <div class="col-sm-4 header-middle-menu">
                    <div class="shop-menu pull-left">
                        <ul class="nav navbar-nav">
                            <li><a href="checkout.html"><i class="fa fa-crosshairs"></i> پرداخت</a></li>
                        </ul>
                    </div>
                </div> -->

                <div class="col-sm-4" style="text-align: left;">
                    <div class="logo">
                        <a href="{% url 'home_page' %}"><img src="{{ site_setting.site_logo.url }}" alt="Logo"
                                                             width="60"
                                                             style="text-align: center;"/></a>
                    </div>
                </div>

                <div class="col-sm-8 header-middle-menu">
                    <div class="shop-menu pull-right">
                        <ul class="nav navbar-nav">
                            {% if request.user.is_authenticated %}
                                {% if request.user.is_superuser %}
                                    <li><a href="/admin"><i class="fa fa-user"></i> پنل ادمین</a></li>
                                {% endif %}
                                <li><a href="{% url 'user_basket_page' %}"><i class="fa fa-shopping-cart"></i> سبد خرید</a>
                                </li>
                                <li><a href="{% url 'user_panel_dashboard' %}"><i class="fa fa-user"></i> پنل
                                    کاربری</a>
                                </li>
                                <li><a href="{% url 'logout_page' %}"><i class="fa fa-sign-out"></i> خروج</a>
                                </li>
                            {% else %}
                                <li><a href="{% url 'register_page' %}"><i class="fa fa-user-plus"></i> ثبت نام</a></li>
                                <li><a href="{% url 'login_page' %}"><i class="fa fa-sign-in"></i> ورود</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">

                <div class="col-sm-3">
                    <div class="search_box pull-left">
                        <input type="text" placeholder="جستـجو"/>
                    </div>
                </div>

                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-right">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li>
                                <a href="{% url 'home_page' %}"
                                   class="{% if request.resolver_match.url_name == 'home_page' %}active{% endif %}">
                                    خـانه
                                </a>
                            </li>
                            <li>
                                <a class="{% if request.resolver_match.url_name == 'product_list' %}active{% endif %}"
                                   href="{% url 'product_list' %}">محصولات</a></li>
                            {% comment %}
                            <li><a
                                    class="{% if request.resolver_match.url_name == 'articles_list' %}active{% endif %}"
                                    href="{% url 'articles_list' %}">مقالات</a></li>
                            {% endcomment %}
                            <li><a
                                    class="{% if request.resolver_match.url_name == 'about_page' %}active{% endif %}"
                                    href="{% url 'about_page' %}">درباره مـا</a></li>

                            <li><a
                                    class="{% if request.resolver_match.url_name == 'contact_us_page' %}active{% endif %}"
                                    href="{% url 'contact_us_page' %}">تماس با مـا</a></li>

                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->